import Link from 'next/link'
import { Check, Sparkles } from 'lucide-react'

const plans = [
  { name: 'Essentiel', price: '0', description: 'Pour démarrer sans engagement', features: ['1 annonce active', '5 photos', 'Visibilité standard'], featured: false },
  { name: 'Visibilité', price: '5 000', description: 'Pour recevoir plus de demandes', features: ['10 annonces actives', 'Badge professionnel', 'Remontée hebdomadaire', 'Statistiques détaillées'], featured: true },
  { name: 'Signature', price: '15 000', description: 'Pour les entreprises ambitieuses', features: ['Annonces illimitées', 'Mise en avant prioritaire', 'Badge vérifié', 'Support prioritaire'], featured: false },
]

export default function PackagesPage() { return <main className="min-h-screen bg-[#f7f5f0] px-5 py-16 text-[#142230] sm:px-8"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-[#d6533c]">Pour les propriétaires</p><h1 className="mt-4 font-serif text-5xl font-bold tracking-tight">Faites grandir votre présence.</h1><p className="mt-5 text-lg leading-8 text-[#687582]">Choisissez la formule qui correspond à votre activité et mettez vos annonces sous les projecteurs.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`relative rounded-[1.6rem] border p-7 ${plan.featured ? 'border-[#f26b4f] bg-[#142230] text-[#fffaf4] shadow-[0_20px_50px_rgba(20,34,48,0.18)]' : 'border-[#e4e0d8] bg-[#fffdf9]'}`}>{plan.featured && <span className="absolute right-6 top-6 flex items-center gap-1 rounded-full bg-[#f26b4f] px-3 py-1 text-xs font-semibold"><Sparkles size={13} /> Populaire</span>}<h2 className="font-serif text-3xl font-bold">{plan.name}</h2><p className={`mt-2 text-sm ${plan.featured ? 'text-[#fffaf4]/65' : 'text-[#687582]'}`}>{plan.description}</p><div className="mt-8"><span className="font-serif text-4xl font-bold">{plan.price}</span><span className={plan.featured ? 'text-[#fffaf4]/65' : 'text-[#687582]'}> F CFA / mois</span></div><ul className="mt-8 flex flex-col gap-4">{plan.features.map(feature => <li key={feature} className="flex items-center gap-3 text-sm"><span className={`flex size-6 items-center justify-center rounded-full ${plan.featured ? 'bg-[#f26b4f]' : 'bg-[#fce5de] text-[#d6533c]'}`}><Check size={14} /></span>{feature}</li>)}</ul><Link href="/publier" className={`mt-9 block rounded-xl px-4 py-3 text-center text-sm font-semibold ${plan.featured ? 'bg-[#fffaf4] text-[#142230]' : 'bg-[#142230] text-[#fffaf4]'}`}>Choisir cette formule</Link></article>)}</div></div></main> }
